---
abstract: 'Low level api for Aleph X Services'
author:
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-AlephX
provides:
  Catmandu::AlephX:
    file: lib/Catmandu/AlephX.pm
    version: 1.0
  Catmandu::AlephX::Metadata:
    file: lib/Catmandu/AlephX/Metadata.pm
    version: 0
  Catmandu::AlephX::Metadata::MARC:
    file: lib/Catmandu/AlephX/Metadata/MARC.pm
    version: 0
  Catmandu::AlephX::Metadata::MARC::Aleph:
    file: lib/Catmandu/AlephX/Metadata/MARC/Aleph.pm
    version: 0
  Catmandu::AlephX::Op::BorAuth:
    file: lib/Catmandu/AlephX/Op/BorAuth.pm
    version: 0
  Catmandu::AlephX::Op::BorInfo:
    file: lib/Catmandu/AlephX/Op/BorInfo.pm
    version: 0
  Catmandu::AlephX::Op::CircStatM:
    file: lib/Catmandu/AlephX/Op/CircStatM.pm
    version: 0
  Catmandu::AlephX::Op::CircStatus:
    file: lib/Catmandu/AlephX/Op/CircStatus.pm
    version: 0
  Catmandu::AlephX::Op::Find:
    file: lib/Catmandu/AlephX/Op/Find.pm
    version: 0
  Catmandu::AlephX::Op::FindDoc:
    file: lib/Catmandu/AlephX/Op/FindDoc.pm
    version: 0
  Catmandu::AlephX::Op::GetHolding:
    file: lib/Catmandu/AlephX/Op/GetHolding.pm
    version: 0
  Catmandu::AlephX::Op::IllBorInfo:
    file: lib/Catmandu/AlephX/Op/IllBorInfo.pm
    version: 0
  Catmandu::AlephX::Op::IllGetDoc:
    file: lib/Catmandu/AlephX/Op/IllGetDoc.pm
    version: 0
  Catmandu::AlephX::Op::IllGetDocShort:
    file: lib/Catmandu/AlephX/Op/IllGetDocShort.pm
    version: 0
  Catmandu::AlephX::Op::IllLoanInfo:
    file: lib/Catmandu/AlephX/Op/IllLoanInfo.pm
    version: 0
  Catmandu::AlephX::Op::ItemData:
    file: lib/Catmandu/AlephX/Op/ItemData.pm
    version: 0
  Catmandu::AlephX::Op::ItemDataMulti:
    file: lib/Catmandu/AlephX/Op/ItemDataMulti.pm
    version: 0
  Catmandu::AlephX::Op::Present:
    file: lib/Catmandu/AlephX/Op/Present.pm
    version: 0
  Catmandu::AlephX::Op::PublishAvail:
    file: lib/Catmandu/AlephX/Op/PublishAvail.pm
    version: 0
  Catmandu::AlephX::Op::ReadItem:
    file: lib/Catmandu/AlephX/Op/ReadItem.pm
    version: 0
  Catmandu::AlephX::Record:
    file: lib/Catmandu/AlephX/Record.pm
    version: 0
  Catmandu::AlephX::Record::Present:
    file: lib/Catmandu/AlephX/Record/Present.pm
    version: 0
  Catmandu::AlephX::Response:
    file: lib/Catmandu/AlephX/Response.pm
    version: 0
  Catmandu::AlephX::XPath::Helper:
    file: lib/Catmandu/AlephX/XPath/Helper.pm
    version: 0
  Catmandu::Importer::AlephX:
    file: lib/Catmandu/Importer/AlephX.pm
    version: 0.02
recommends:
  Term::ReadKey: 0
requires:
  Carp: 0
  Catmandu: 0
  Data::Util: 0
  LWP::UserAgent: 0
  Moo: 0
  URI::Escape: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0
